### ISSUE TITLE
Broken URL in Readme.md

### ISSUE THREAD

**Issue by DoctorWkt** [ZipCPU/debouncer#1]
In Readme.md, change https://github.com/ZipCPU/wbscope.html to https://github.com/ZipCPU/wbscope to fix a broken link.

**Comment by gojimmypi** [comment]
this one, too for debouncing buttons, should be:

https://zipcpu.com/blog/2017/08/04/debouncing.html

**Comment by ZipCPU** [comment]
Both links have been fixed.  Thanks for letting me know!

Dan
